### ISSUE TITLE
Linking Time

### ISSUE THREAD

**Issue by Lokathor** [rust-gamedev/wg#50]
There was a [reddit thread](https://www.reddit.com/r/rust_gamedev/comments/cxwo35/experience_using_rust_for_game_dev_so_far/) I just saw in the rust_gamedev group, and many people were reporting _specifically_ that link times were killing the development flow.

I figured it needed a tracker/complaint issue here.

**Comment by est31** [comment]
Personally, I use two workarounds for this:

* First, I use lld instead of GNU bfd. lld is [usually faster](https://lld.llvm.org/#performance) and it was faster in my own benchmarks too. It also supports threads. 
* Second, sometimes I disable debuginfo. A large part of linking time is spent in copying debuginfo over. This problem is so enormous that sometimes debug builds take longer for me than release builds. A remedy is disabling debug info and only turning it on when I want to actually debug a crash/panic/etc. I haven't tested it but I think the [profile-overrides](https://github.com/rust-lang/rust/issues/48683) feature will help with this as well: using it you can turn off debuginfo for your dependencies and only have debuginfo in your own code, which is where most of your debugging happens :). [This](https://github.com/rust-lang/rust/issues/34651) issue might also help with speeding up builds due to debuginfo, I'm not sure.

This is the `~/.cargo/config` snippet I have to use lld:
```toml
# This speeds up small changes dramatically.
# With lld enabled, doing a small change and then
# recompiling takes 0,789s in total on a project of mine.
# Without lld, the same change takes 1,842s.
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]
```

Disabling debuginfo on a per-project basis is easy as well: [example commit](https://github.com/est31/cargo-udeps/commit/e550d93c7a6d756e639ecd7f117ea9f9328d3b38).
